package com.zenith.util.config;

import com.google.common.collect.Lists;
import com.google.gson.annotations.SerializedName;
import com.zenith.feature.chatschema.ChatSchema;
import com.zenith.feature.tasks.Task;
import com.zenith.feature.waypoints.Waypoint;
import com.zenith.feature.whitelist.PlayerEntry;
import com.zenith.mc.item.ItemRegistry;
import com.zenith.module.impl.ActiveHours.ActiveTime;
import it.unimi.dsi.fastutil.ints.IntArraySet;
import it.unimi.dsi.fastutil.objects.ObjectArraySet;
import lombok.Getter;
import org.geysermc.mcprotocollib.network.ProxyInfo;
import org.geysermc.mcprotocollib.protocol.data.game.entity.type.EntityType;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

import java.util.*;

@NullMarked
public final class Config {
    public final String warning = "DO NOT EDIT THIS FILE MANUALLY. Use commands to configure settings";
    public final Authentication authentication = new Authentication();
    public final Client client = new Client();
    public final Debug debug = new Debug();
    public final Server server = new Server();
    public final Plugins plugins = new Plugins();
    public final InteractiveTerminal interactiveTerminal = new InteractiveTerminal();
    public final InGameCommands inGameCommands = new InGameCommands();
    public final Theme theme = new Theme();
    public final Discord discord = new Discord();
    public final Database database = new Database();
    public final AutoUpdater autoUpdater = new AutoUpdater();

    public static final class Authentication {
        public AccountType accountType = AccountType.DEVICE_CODE;
        // only used for MSA
        public String email = "not@set.com";
        public String password = "abc123";
        // updated on successful login
        public String username = "Unknown";
        public boolean prio = false;
        public boolean authTokenRefresh = true;
        public int msaLoginAttemptsBeforeCacheWipe = 2;
        public boolean openBrowserOnLogin = true;
        public boolean alwaysRefreshOnLogin = false;
        public int maxRefreshIntervalMins = 360; // 6 hrs
        public boolean useClientConnectionProxy = false;

        public enum AccountType {
            @SerializedName("msa") MSA,
            @SerializedName("device_code") DEVICE_CODE,
            @SerializedName("device_code_without_device_token") DEVICE_CODE_WITHOUT_DEVICE_TOKEN,
            @SerializedName("prism") PRISM,
            @SerializedName("offline") OFFLINE
        }
    }

    public static final class Theme {
        public ConfigColor primary = ConfigColor.CYAN;
        public ConfigColor success = ConfigColor.MEDIUM_SEA_GREEN;
        public ConfigColor error = ConfigColor.RUBY;
        public ConfigColor inQueue = ConfigColor.MOON_YELLOW;
    }

    public static final class Client {
        public final Server server = new Server();
        public final ConnectionProxy connectionProxy = new ConnectionProxy();
        public int compressionLevel = -1;
        public boolean autoConnect = false; // auto-connect proxy on process start
        public final ClientViaVersion viaversion = new ClientViaVersion();
        public String bindAddress = "0.0.0.0";
        public boolean maxPlaytimeReconnect = false;
        public long maxPlaytimeReconnectMins = 1440;
        public int defaultClientRenderDistance = 25;
        public final ClientTimeout timeout = new ClientTimeout();
        public final Ping ping = new Ping();
        public final ChatSigning chatSigning = new ChatSigning();
        public final Extra extra = new Extra();
        public final Inventory inventory = new Inventory();
        public final ChatSchemas chatSchemas = new ChatSchemas();
        public final KeepAliveHandling keepAliveHandling = new KeepAliveHandling();
        public double tickRate = 1.0;

        public static final class KeepAliveHandling {
            public KeepAliveMode keepAliveMode = KeepAliveMode.PASSTHROUGH;
            public int keepAliveQueueTimeoutMs = 2000;
            public enum KeepAliveMode {
                PASSTHROUGH,
                INDEPENDENT
            }
        }

        public static final class ChatSchemas {
            public LinkedHashMap<String, ChatSchema> serverSchemas = new LinkedHashMap<>();
        }

        public static final class Inventory {
            public int actionDelayTicks = 5;
            public boolean autoCloseOpenContainers = true;
            public int autoCloseOpenContainerAfterSeconds = 60;
            public boolean ncpStrict = false;
        }

        public static final class ChatSigning {
            public boolean enabled = true;
            public boolean force = false;
            public boolean signCommands = true;
        }

        public static final class ClientViaVersion {
            public boolean enabled = false;
            public boolean disableOn2b2t = true;
            public boolean autoProtocolVersion = true;
            public int protocolVersion = 765;
        }

        public static final class ClientTimeout {
            public boolean enable = true;
            public int seconds = 60;
        }

        public static final class Ping {
            public int pingIntervalSeconds = 5;
            public int pingQueueTimeoutMs = 2000;
        }

        public static final class Extra {
            public final AntiAFK antiafk = new AntiAFK();
            public final Spook spook = new Spook();
            public final Utility utility = new Utility();
            public final AutoReconnect autoReconnect = new AutoReconnect();
            public final AutoRespawn autoRespawn = new AutoRespawn();
            public final Spammer spammer = new Spammer();
            public final AutoReply autoReply = new AutoReply();
            public final Stalk stalk = new Stalk();
            public final AutoEat autoEat = new AutoEat();
            public final AutoFish autoFish = new AutoFish();
            public final KillAura killAura = new KillAura();
            public final AutoTotem autoTotem = new AutoTotem();
            public final AntiLeak antiLeak = new AntiLeak();
            public final Chat chat = new Chat();
            public final AntiKick antiKick = new AntiKick();
            public final ReplayMod replayMod = new ReplayMod();
            public final ArrayList<PlayerEntry> friendsList = new ArrayList<>();
            public boolean autoConnectOnLogin = true;
            public boolean prioStatusChangeMention = true;
            public boolean killMessage = true;
            public boolean logChatMessages = true;
            public boolean logOnlyQueuePositionUpdates = true;
            public boolean reconfiguringNotification = true;
            public final CoordObfuscation coordObfuscation = new CoordObfuscation();
            public final ActionLimiter actionLimiter = new ActionLimiter();
            public final VisualRange visualRange = new VisualRange();
            public final AutoArmor autoArmor = new AutoArmor();
            public final AutoMend autoMend = new AutoMend();
            public final QueueWarning queueWarning = new QueueWarning();
            public final Click click = new Click();
            public final SessionTimeLimit sessionTimeLimit = new SessionTimeLimit();
            public final AutoOmen autoOmen = new AutoOmen();
            public final Pathfinder pathfinder = new Pathfinder();
            public final SpawnPatrol spawnPatrol = new SpawnPatrol();
            public final PearlLoader pearlLoader = new PearlLoader();
            public final Waypoints waypoints = new Waypoints();
            public final AutoDrop autoDrop = new AutoDrop();
            public String whisperCommand = "msg";
            public int tpsBufferSize = 20;
            public final Tasks tasks = new Tasks();
            public final AquariusMiner aquariusMiner = new AquariusMiner();

            public static final class Tasks {
                public boolean enabled = true;
                public final LinkedHashMap<String, Task> tasks = new LinkedHashMap<>();
                public boolean logCommandActionOutput = true;
                public boolean taskCommandExecutedNotification = true;
            }

            /**
             * AquariusMiner — AFK bulk single-block quarry miner (baked in from the standalone
             * AquariusMiner plugin). Quarries a chunk within a Y band then spirals to the next.
             * Read everywhere via {@code CONFIG.client.extra.aquariusMiner.*}.
             */
            public static class AquariusMiner {
                /** How a finite mining area is defined (or Unlimited = infinite outward spiral). */
                public enum AreaMode { Unlimited, ChunksFromStart, Corners }

                /** Where a ChunksFromStart box sits relative to the chunk the bot is in when enabled. */
                public enum AreaAnchor { Center, Corner }

                /** Whether the module is enabled on startup. */
                public boolean enabled = false;

                /**
                 * Lowest Y level the quarry will mine (inclusive). Default sits just above bedrock
                 * in the 1.21 deepslate layer.
                 */
                public int minY = -59;

                /** Highest Y level the quarry will mine (inclusive). A thin band keeps holes shallow. */
                public int maxY = -50;

                // --- area ---

                /**
                 * How the mining area is bounded. Unlimited = infinite outward chunk spiral from where the
                 * bot is when enabled. ChunksFromStart = a width x length box of chunks placed by
                 * {@link #areaAnchor}. Corners = an explicit box between two X/Z coordinates (Y uses the
                 * minY/maxY band). When a finite area is fully cleared the bot stores any remaining haul and
                 * the run completes.
                 */
                public AreaMode areaMode = AreaMode.Unlimited;

                /**
                 * ChunksFromStart only: where the box sits relative to the start chunk. Center = the bot is
                 * in the middle. Corner = the start chunk is a corner and the box extends in the direction
                 * the bot is FACING (so face the area before enabling). Set width = length for a square.
                 */
                public AreaAnchor areaAnchor = AreaAnchor.Center;

                /** ChunksFromStart only: area size along X, in chunks (1 chunk = 16 blocks). */
                public int areaWidthChunks = 3;

                /** ChunksFromStart only: area size along Z, in chunks (1 chunk = 16 blocks). */
                public int areaLengthChunks = 3;

                /** Corners only: first corner X/Z (block coords). The Y span comes from minY/maxY. */
                public int corner1X = 0;
                public int corner1Z = 0;
                /** Corners only: second corner X/Z (block coords). */
                public int corner2X = 0;
                public int corner2Z = 0;

                /** Ticks between mining drive steps / starting the next chunk (pacing, anti-spam). */
                public int delayTicks = 4;

                /** Drop "junk" items while mining so the inventory fills with keep-items only. */
                public boolean dropJunk = true;

                /** Ticks between junk-drop attempts. */
                public int junkDropDelayTicks = 10;

                /**
                 * Drop ANYTHING that isn't deliberately retained, not just the {@link #junkItems} list. Protected
                 * (never dropped): {@link #keepItems}, shulker boxes, the ender chest, {@link #storageItems}, tools
                 * (damageable gear), and good food. With this on the inventory fills with keep-items only - stray
                 * cobblestone, dirt, gravel, ores you don't keep, etc. are all tossed (mirrors the Foreman mod, which
                 * drops anything that isn't a target/tool/food/echest/shulker). Off = legacy blacklist-only behaviour
                 * (drop just the {@link #junkItems} below). Only applies when {@link #dropJunk} is on.
                 */
                public boolean dropNonKeep = true;

                /**
                 * Explicit always-drop list (in addition to {@link #dropNonKeep}'s catch-all). A keep-item is never
                 * dropped even if it appears here - {@link #keepItems} takes precedence - so a default entry like
                 * "tuff" is harmless once tuff is added to the keep-list.
                 */
                public List<String> junkItems = new ArrayList<>(List.of(
                    "cobblestone", "stone", "diorite", "granite", "andesite",
                    "gravel", "dirt", "smooth_basalt"
                ));

                /**
                 * Also drop "risky" foods (see {@link #riskyFoods}) as junk. Normal foods (bread, cooked
                 * meat, carrots, golden apples) are NOT in that list, so they're kept for an AutoEat module.
                 * Only applies when {@link #dropJunk} is on.
                 */
                public boolean dropBadFood = true;

                /**
                 * Foods treated as junk when {@link #dropBadFood} is on: harmful-effect / teleport foods and
                 * the (non-stackable) stews. Kept out of the main {@link #junkItems} list so it can be toggled
                 * separately.
                 */
                public List<String> riskyFoods = new ArrayList<>(List.of(
                    "rotten_flesh", "spider_eye", "poisonous_potato", "pufferfish",
                    "chicken", "chorus_fruit",
                    "suspicious_stew", "mushroom_stew", "rabbit_stew", "beetroot_soup"
                ));

                /**
                 * The items the miner keeps and stores - the haul. Everything mined that isn't on this list is
                 * dropped (when {@link #dropNonKeep} is on), the inventory-full trigger counts only these, and
                 * shulkers are filled with them. Default is a normal-pickaxe deepslate quarry (cobbled_deepslate +
                 * tuff); add "deepslate" if you mine WITH silk touch. Editable at runtime via the keep command.
                 */
                public List<String> keepItems = new ArrayList<>(List.of(
                    "cobbled_deepslate", "tuff"
                ));

                /**
                 * Only begin a storage cycle once the inventory is COMPLETELY packed — every keep stack at its
                 * max count and no empty slots left — so shulkers fill with whole stacks. Turn off to use the
                 * looser {@link #freeSlotsBeforeFull} margin instead (which can fire on partial stacks).
                 */
                public boolean requireFullStacks = true;

                /**
                 * Used only when {@link #requireFullStacks} is false. When the number of empty main-inventory
                 * slots drops to this value or below, the inventory is considered full and the storage cycle
                 * runs (or mining pauses if storage is disabled / no storage item is available).
                 */
                public int freeSlotsBeforeFull = 1;

                // --- storage cycle ---
                // PRIMARY model (mirrors the Foreman mod): whenever the bot carries an ENDER CHEST it is the field
                // buffer - an empty shulker is pulled out of it, filled with the haul, and the FILLED shulker is
                // stored back INTO the ender chest. Filled shulkers are never left on the ground or carried in the
                // mining inventory. The settings below are only the FALLBACK for when no ender chest is carried.

                /**
                 * FALLBACK (no ender chest): when the inventory fills, place a shulker beside the bot and deposit
                 * {@link #keepItems} into it. If false (and no ender chest), mining simply pauses when full. Ignored
                 * when an ender chest is carried (the ender-chest buffer is used instead).
                 */
                public boolean storageEnabled = true;

                /**
                 * FALLBACK only (no ender chest): after depositing into the placed shulker, break it and pick it up
                 * again (carry it) instead of leaving it behind full. Has no effect when an ender chest is carried -
                 * there, filled shulkers always go back into the chest.
                 */
                public boolean breakAndCollect = false;

                /**
                 * Extra exact item names to treat as a storage container. Any "*_shulker_box" is detected
                 * automatically; add e.g. "ender_chest" here to use one.
                 */
                public List<String> storageItems = new ArrayList<>();

                /** Ticks between individual deposit shift-clicks (lets the inventory cache settle). */
                public int depositDelayTicks = 2;

                /**
                 * Ticks a single storage step (place / open / close / break / pickup) may wait before the
                 * cycle is aborted and mining pauses. 20 ticks/sec.
                 */
                public int storeStepTimeoutTicks = 300;

                /**
                 * Settle delay (ticks) the storage cycle waits BEFORE each rotation-driven action — placing,
                 * opening/right-clicking, and breaking the ender chest / shulker. 2b2t's movement & rotation
                 * anticheat is strict and the cycle otherwise fires these back-to-back (one per tick), which
                 * desyncs the bot's position and trips "entity blocking the place position" / place timeouts.
                 * Higher = slower but far more 2b2t-legit. 10 ticks = 0.5s; raise on a laggy/high-ping link.
                 */
                public int storeStepSettleTicks = 10;

                /**
                 * Break the field ender chest with a SILK-TOUCH pickaxe so it drops as an ENDER CHEST and is recovered
                 * — not the 8 obsidian a normal/fortune pick yields (which destroys the chest). The bot picks a
                 * silk-touch pickaxe from its inventory just for that break, then mining returns to its normal tool.
                 * Keep a silk-touch pickaxe on the bot. If this is ON and none is found, the cycle pauses (after the
                 * haul is already stored safely) rather than destroy the chest. Turn OFF only if you accept losing the
                 * ender chest each cycle. Shulkers are unaffected (they drop themselves with any tool).
                 */
                public boolean silkTouchEchest = true;

                /**
                 * DRY-RUN diagnostic (default off). When the storage cycle opens the ender chest, log every
                 * shulker inside it - item name, custom name, inner-stack count, and the empty/full verdict the
                 * bot would use to pick a buffer - then ABORT without pulling or storing anything (the echest is
                 * recovered and mining pauses). Use this to verify the server actually sends shulker contents so
                 * the bot can tell empty buffers from your valuable full shulkers. If a full/named shulker logs
                 * "0 inner stacks, isEmpty=true", content-reading is broken and storage is unsafe on that account.
                 */
                public boolean dryRunStorage = false;

                /**
                 * Safety cap: if a single chunk's clear runs this many ticks without finishing
                 * (e.g. the box reaches into an unloaded chunk), force-advance to the next chunk.
                 * 20 ticks/sec, so 3600 = 3 minutes.
                 */
                public int maxClearTicks = 3600;

                /**
                 * After a sub-box clears (or times out), VERIFY it: scan that cell for any solid blocks still
                 * standing. A lag spike / desync can make clearArea report a box DONE (or give up on the stall
                 * cap) with blocks left, leaving gaps. If leftovers are found, re-issue the SAME sub-box up to
                 * {@link #clearRetries} times before moving on.
                 */
                public boolean verifyClears = true;

                /** Max times to re-run a sub-box that still has blocks after a clear/stall (see {@link #verifyClears}). */
                public int clearRetries = 2;

                // --- mining style ---

                /**
                 * LEGIT mining (line-of-sight). On (default), the bot breaks ONLY blocks it can actually see - the
                 * same reach/sightline the server enforces - instead of letting the quarry engine "ghost-hand" through
                 * walls to occluded blocks. It breaks the nearest visible block and repositions when none is in view,
                 * so a quarry mines from exposed faces inward like a player would. Turn OFF for the faster batch engine
                 * (which can reach through blocks) when looking legit doesn't matter. Slightly slower while on.
                 */
                public boolean legitMine = true;

                // --- drop collection ---

                /**
                 * Clear each chunk in clearBoxSize x clearBoxSize sub-boxes (full height) instead of the whole
                 * 16x16 chunk in one go. The bot repositions between sub-boxes and walks back over the ground it
                 * just dug, so it picks up the drops instead of leaving them on the floor to despawn. Smaller =
                 * more thorough collection (more repositioning); 16 = the whole chunk at once (old behaviour).
                 */
                public int clearBoxSize = 8;

                /**
                 * Mine a bounded area in horizontal LAYERS this many blocks tall, TOP-DOWN: the bot clears this
                 * slice across the whole area before dropping to the next, so it never tunnels one cell to minY
                 * while the rest stands untouched. 1 = peel one block-level at a time across the area (most even,
                 * most travel); larger = fewer full-area passes (faster) but it digs this many deep per spot first.
                 * Set it to your full Y band (maxY-minY+1) for the old per-cell full-height behaviour. The
                 * unbounded spiral always clears full-height per chunk (no infinite top to pre-sweep).
                 */
                public int layerHeight = 1;

                /**
                 * After each sub-box clears, do a VACUUM pass: walk over every kept item (in {@link #keepItems})
                 * still lying on the ground in that box and pick it up before moving on, so nothing despawns.
                 * Time-capped by {@link #collectMaxSeconds} and skips anything unreachable, so it can't hang.
                 */
                public boolean collectDrops = true;

                /** Cap (seconds) on the vacuum pass per sub-box; past it, the bot gives up the stragglers and moves on. */
                public int collectMaxSeconds = 20;

                // --- deposit chests (haul filled shulkers to a base) ---
                // Adds base trips ON TOP of the ender-chest buffer for a near-unlimited run. The buffer always
                // stores filled shulkers back into the ender chest; with this on, once the chest fills with filled
                // shulkers the bot hauls them to fixed DEPOSIT chests at a base, then visits a separate SUPPLY chest
                // to restock empty shulkers. With this OFF, the run simply ends once the ender chest is packed full.
                // Chest locations are set by command (the proxy is headless, so there is no in-world crosshair).

                /** Add base-chest hauling trips on top of the ender-chest buffer (off = end the run when the chest is full). */
                public boolean depositToChests = false;

                /** DEPOSIT chest locations ("x y z" each) where FILLED shulkers are dropped off. */
                public List<String> depositChests = new ArrayList<>();

                /**
                 * SUPPLY chest locations ("x y z" each) where EMPTY shulkers are taken from. Keep these SEPARATE
                 * from the deposit chests. Only used when {@link #refillEmpties} is on.
                 */
                public List<String> supplyChests = new ArrayList<>();

                // (No "deposit after N shulkers" knob: the ender chest is the field buffer, so a trip fires once it
                // runs out of empties - the batch size is just how many empty shulkers you keep stocked / refill.)

                /**
                 * On a trip, after dropping off filled shulkers, visit a supply chest and pull a fresh batch of
                 * empty shulkers. This is what makes a run effectively unlimited. Off = drop-offs only, and the
                 * run ends when the empties you started with run out.
                 */
                public boolean refillEmpties = true;

                /** How many empty shulkers to grab from a supply chest per trip. */
                public int emptiesPerTrip = 6;

                /** Don't walk to a chest farther than this many blocks (straight-line); past it the bot pauses. 0 = no limit. */
                public int maxDepositDistance = 1024;

                // --- cave handling ---
                // Relax ZenithProxy's pathfinder fall/jump limits while the module is active so the bot drops
                // into caves to reach blocks instead of detouring or stalling. These are pushed into
                // CONFIG.client.extra.pathfinder.* on enable and restored on disable. Lava is still never
                // walked/fallen into (the pathfinder costs it out). Balanced defaults; raise for more reach.

                /** Master toggle for the relaxed cave movement profile below. */
                public boolean caveHandling = true;

                /** Tallest no-water drop the bot will take (pathfinder maxFallHeightNoWater; stock default 3). */
                public int maxFallHeight = 20;

                /** Allow placing a block mid-jump to bridge a parkour gap (pathfinder allowParkourPlace). */
                public boolean allowParkourPlace = true;

                /** Allow stepping diagonally downward into caves (pathfinder allowDiagonalDescend). */
                public boolean allowDiagonalDescend = true;

                /** Allow running parkour jumps across gaps (pathfinder allowParkour). Off for Balanced. */
                public boolean allowParkour = false;

                /** Allow stepping diagonally upward (pathfinder allowDiagonalAscend). Off for Balanced. */
                public boolean allowDiagonalAscend = false;

                // --- safety / lifecycle ---

                /**
                 * When the run ends — the finite area is fully cleared, or storage is exhausted (no shulkers
                 * left / chest full) — also disconnect the bot from the server. Handy for an AFK run so it
                 * leaves cleanly once everything is packed. Off = just stop and stay connected.
                 */
                public boolean autoDisconnect = false;

                /** Pause mining while another (non-self) player is within {@link #playerPauseRange} blocks. */
                public boolean pauseOnPlayer = true;

                /** Range in blocks for {@link #pauseOnPlayer}. */
                public double playerPauseRange = 48.0;

                // --- tool restock ---

                /**
                 * When the bot runs out of fresh tools, run a restock cycle: place the {@link #restockSourceItem}
                 * (an ender chest), pull out the tool-shulker (a shulker that contains a fresh tool), place it,
                 * take a fresh tool, break and recover the shulker, put it back in the ender chest, then recover
                 * the chest. Lets one ender-chest slot hold a whole shulker of spare pickaxes.
                 *
                 * SETUP: the tool-shulker must be a DIFFERENT colour from any empty loot shulkers you carry —
                 * the bot places shulkers by item type, so a unique colour guarantees it places the right one.
                 */
                public boolean restockTools = false;

                /** The source container the tool-shulker lives in (placed/opened during a restock). */
                public String restockSourceItem = "ender_chest";

                /** Remaining-durability threshold below which a tool is considered spent and gets restocked. */
                public int restockBelowDurability = 60;

                /** Item-name suffix identifying the tool to restock (e.g. "pickaxe", "shovel"). */
                public String restockToolKeyword = "pickaxe";

                /**
                 * Also keep a fresh SHOVEL alongside the main restock tool, so gravel/sand mines fast instead of
                 * being slogged through with a pickaxe. The tool-shulker must also hold spare shovels. Off, or when
                 * {@link #restockToolKeyword} is already "shovel", this does nothing.
                 */
                public boolean alsoRestockShovel = true;

                // --- packet sniffer (debug) ---
                // A separate module that taps ZenithProxy's CLIENT_REGISTRY (bot <-> 2b2t): every packet to/from the
                // server is captured into a rolling {@link #sniffBufferLines}-line buffer, dumpable on demand. Enabling
                // it registers the codec; disabling unregisters it (zero overhead when off). See /aquariusminer sniff.

                /** Master toggle for the packet sniffer. Enabling registers the client packet codec. */
                public boolean sniffEnabled = false;

                /** Also log every captured packet live as it arrives (vs. quietly filling the rolling buffer only). */
                public boolean sniffLive = false;

                /** Include the full packet contents (toString) instead of just the class name. */
                public boolean sniffBody = false;

                /** Which direction to capture: "in" (from server), "out" (to server), or "both". */
                public String sniffDir = "both";

                /** Only capture packets whose class name contains this (case-insensitive). Empty = no filter. */
                public String sniffFilter = "";

                /** Scenario template name limiting capture to a packet group (e.g. movement/combat/chunks). Empty = all. */
                public String sniffTemplate = "";

                /** The rolling buffer keeps only the most recent N captured lines (oldest evicted). */
                public int sniffBufferLines = 250;

                // --- food restock ---
                // 2b bots keep food (golden carrots, enchanted/normal golden apples, cooked meat) in a FOOD-SHULKER
                // inside the ender chest. The built-in AutoEat module eats it; this tops it up. When the carried food
                // drops below {@link #minFoodOnHand} the bot cracks that food-shulker - the SAME place/open/take/break/
                // return cycle as the tool-shulker - and refills by preference: golden carrot > enchanted golden apple
                // > golden apple > cooked > other safe food (safety per ZenithProxy's food registry; risky foods are
                // never taken). It triggers on COUNT, not hunger, so food is staged before AutoEat goes hungry.
                // BEST-EFFORT: with no food-shulker in the ender chest the bot just warns and keeps mining (no pause).

                /** Restock food from a FOOD-SHULKER in the ender chest when the carried food runs low. */
                public boolean restockFood = false;

                /** Trigger the food restock when the total carried (safe) food drops below this count. 1 = last bite. */
                public int minFoodOnHand = 1;

                /** Take food from the shulker until the carried (safe) food reaches this count (or the shulker empties). */
                public int foodRestockCount = 64;
            }

            public static final class Waypoints {
                public ArrayList<Waypoint> waypoints = new ArrayList<>();
            }

            public static final class PearlLoader {
                public ArrayList<Pearl> pearls = new ArrayList<>();
                public boolean returnToStartPos = true;

                /**
                 * @param id player name or some other unique identifier
                 * @param x  the position of the block we need to interact with to load the pearl
                 */
                public record Pearl(String id, int x, int y, int z) { }
            }

            public static final class Pathfinder {
                public @Nullable Integer priority = null;
                public boolean allowBreak = true;
                public boolean allowSprint = false;
                public boolean allowPlace = true;
                public boolean allowInventory = true;
                public boolean allowDownward = true;
                public boolean allowParkour = false;
                public boolean allowParkourPlace = false;
                public boolean allowParkourAscend = false;
                public boolean allowDiagonalDescend = false;
                public boolean allowDiagonalAscend = false;
                public boolean diagonalCentering = false;
                public boolean traverseCentering = false;
                public double blockPlacementPenalty = 20.0;
                public double blockBreakAdditionalCost = 2;
                public double jumpPenalty = 2.0;
                public double lavaWalkCost = 200;
                public int maxFallHeightNoWater = 3;
                public boolean allowLongFall = false;
                public double longFallCostLogMultiplier = 50;
                public double longFallCostAddCost = 100;
                public int followRadius = 2;
                public int teleportDelayMs = 500;
                public boolean renderPath = true;
                public int pathRenderIntervalTicks = 10;
                public boolean renderPathDetailed = false;
                public int primaryTimeoutMs = 500;
                public int failureTimeoutMs = 2000;
                public int planAheadPrimaryTimeoutMs = 4000;
                public int planAheadFailureTimeoutMs = 5000;
                public int failedPathSearchCooldownMs = 1000;
                public boolean getToBlockExploreForBlocks = true;
                public boolean getToBlockBlacklistClosestOnFailure = false;
                public boolean simplifyUnloadedYGoal = false;
                public boolean placeBlockVerifyAbleToPlace = true;
                public int interactWithProcessMaxPathTries = 5;
                public boolean avoidUpdatingFallingBlocks = true;
                public boolean pauseMiningForFallingBlocks = true;
                public boolean autoTool = true;
                public boolean assumeExternalAutoTool = false;
                public boolean itemSaver = false;
                public int itemSaverThreshold = 5;
                public boolean preferSilkTouch = false;
                public final Set<String> acceptableThrowawayItems = new ObjectArraySet<>(new String[]{
                    ItemRegistry.DIRT.name(),
                    ItemRegistry.COBBLESTONE.name(),
                    ItemRegistry.NETHERRACK.name(),
                    ItemRegistry.STONE.name(),
                    ItemRegistry.OBSIDIAN.name(),
                    ItemRegistry.CRYING_OBSIDIAN.name(),
                    ItemRegistry.BIRCH_PLANKS.name(),
                    ItemRegistry.JUNGLE_PLANKS.name(),
                    ItemRegistry.SPRUCE_PLANKS.name(),
                    ItemRegistry.DARK_OAK_PLANKS.name(),
                    ItemRegistry.ACACIA_PLANKS.name(),
                    ItemRegistry.WARPED_PLANKS.name(),
                    ItemRegistry.CHERRY_PLANKS.name(),
                    ItemRegistry.OAK_PLANKS.name()
                });
                public final Set<String> allowBreakAnyway = new ObjectArraySet<>();
            }

            public static class SessionTimeLimit {
                public boolean enabled = true;
                public IntArraySet ingameNotificationPositions = IntArraySet.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
                public IntArraySet discordNotificationPositions = new IntArraySet();
                public IntArraySet discordMentionPositions = new IntArraySet();
                public boolean dynamic2b2tSessionTimeLimit = true;
            }

            public static class Click {
                public @Nullable Integer priority = null;
                public boolean enabled = true;
                public boolean holdLeftClick = false;
                public boolean holdRightClick = false;
                public boolean hasRotation = false;
                public boolean holdSneak = false;
                public float rotationYaw = 0;
                public float rotationPitch = 0;
                public HoldRightClickMode holdRightClickMode = HoldRightClickMode.MAIN_HAND;
                public HoldClickTarget holdClickTarget = HoldClickTarget.ANY;
                public int holdRightClickInterval = 5;
                public int holdLeftClickInterval = 0;
                public float additionalBlockReach = 0;
                public float additionalEntityReach = 0;
                public enum HoldRightClickMode {
                    MAIN_HAND,
                    OFF_HAND,
                    ALTERNATE_HANDS
                }
                public enum HoldClickTarget {
                    ANY,
                    NONE,
                    ENTITY,
                    BLOCK
                }
            }

            public static class SpawnPatrol {
                public @Nullable Integer priority = null;
                public boolean enabled = false;
                public boolean ignoreFriends = true;
                public boolean targetOnlyNakeds = true;
                public boolean targetOnlyBedrock = false;
                public boolean targetAttackers = true;
                public boolean stickyTargeting = true;
                public boolean nether = true;
                public boolean stuckKill = true;
                public int stuckKillSeconds = 60;
                public int stuckKillMinDist = 10;
                public boolean stuckKillAntiStuck = true;
                public int goalX = 0;
                public int goalY = 120;
                public int goalZ = 0;
                public int maxPatrolRange = 500;
                public final ArrayList<PlayerEntry> ignoreList = new ArrayList<>();
            }

            public static final class QueueWarning {
                public boolean enabled = true;
                public IntArraySet warningPositions = IntArraySet.of(1, 2, 3, 10);
                public IntArraySet mentionPositions = new IntArraySet();
            }

            public static class AutoMend {
                public @Nullable Integer priority = null;
                public boolean enabled = false;
            }

            public static class VisualRange {
                public boolean enabled = true;
                public boolean ignoreFriends = false;
                public boolean enterAlert = true;
                public boolean enterAlertMention = true;
                public boolean leaveAlert = true;
                public boolean logoutAlert = true;
                public boolean enterWhisper = false;
                public String enterWhisperMessage = "Hello, I am using ZenithProxy! I have alerted my owner that you are here!";
                public int enterWhisperCooldownSeconds = 30;
                public boolean enterWhisperWhilePlayerConnected = false;
                public boolean replayRecording = false;
                public ReplayRecordingMode replayRecordingMode = ReplayRecordingMode.ENEMY;
                public int replayRecordingCooldownMins = 5;
                public enum ReplayRecordingMode {
                    ENEMY,
                    ALL
                }
            }

            public static class AutoArmor {
                public @Nullable Integer priority = null;
                public boolean enabled = false;
            }

            public static class AntiKick {
                public boolean enabled = false;
                public int playerInactivityKickMins = 15;
                public int minWalkDistance = 2;
            }

            public static final class Chat {
                public boolean enabled = true;
                public final ArrayList<PlayerEntry> ignoreList = new ArrayList<>();
                public boolean hideChat = false;
                public boolean hideWhispers = false;
                public boolean hideDeathMessages = false;
                public boolean showConnectionMessages = false;
                public boolean insertClickableLinks = false;
                public boolean hide2b2tActionBarText = false;
                public boolean replace2b2tChatCommands = false;
                public boolean ignoreReplace2b2tChatCommandWhileDatabaseOn = true;
                public boolean prefixChats = false;
                public String prefix = ">";
                public boolean suffixChats = false;
                public String suffix = "| Sent from my ZenithProxy";
                public boolean randomSuffix = false;
            }

            public static final class AutoTotem {
                public @Nullable Integer priority = null;
                public boolean enabled = true;
                public boolean inGame = false;
                public int healthThreshold = 20;
                public boolean noTotemsAlert = false;
                public boolean noTotemsAlertMention = false;
                public boolean totemPopAlert = false;
                public boolean totemPopAlertMention = false;
            }

            public static final class AntiLeak {
                public boolean enabled = true;
                // checks if numbers in chat are within a range from your coords
                public boolean rangeCheck = true;
                // the factor to divide and multiply your coords by to get the range
                public double rangeFactor = 10.0;
            }

            public static final class KillAura {
                public @Nullable Integer actionPriority = null;
                public boolean enabled = false;
                public boolean targetPlayers = false;
                public boolean targetHostileMobs = true;
                public boolean targetNeutralMobs = false;
                public boolean targetCustom = false;
                public boolean onlyNeutralAggressive = false;
                public boolean onlyHostileAggressive = false;
                public boolean switchWeapon = true;
                public boolean targetArmorStands = false; // soft deprecated
                public int attackDelayTicks = 10;
                // When enabled, adjusts attackDelayTicks by current server TPS
                // so attack rate stays consistent.
                public boolean tpsSync = false;
                public boolean raycast = false;
                public final ArrayList<EntityType> customTargets = new ArrayList<>();
                public Priority priority = Priority.NONE;
                public WeaponType weaponType = WeaponType.ANY;
                public WeaponMaterial weaponMaterial = WeaponMaterial.ANY;

                public enum Priority {
                    NONE,
                    NEAREST
                }

                public enum WeaponType {
                    ANY,
                    SWORD,
                    AXE
                }

                public enum WeaponMaterial {
                    ANY,
                    NETHERITE,
                    DIAMOND
                }
            }

            public static final class AutoEat {
                public @Nullable Integer priority = null;
                public boolean enabled = true;
                public int healthThreshold = 10;
                public int hungerThreshold = 10;
                public boolean warning = true;
                public boolean warningMention = false;
                public boolean allowUnsafeFood = false;
                public Mode mode = Mode.ALL;
                public enum Mode {
                    ALL,
                    BLACKLIST,
                    WHITELIST
                }
                public HashSet<String> foods = new HashSet<>();
            }

            public static final class AutoOmen {
                public @Nullable Integer priority = null;
                public boolean enabled = false;
                public boolean whileRaidActive = false;
                public boolean whileOmenActive = false;
                public int raidCooldownMs = 1000;
                public int omenCooldownMs = 1000;
            }

            public static final class Stalk {
                public boolean enabled = false;
                public final ArrayList<PlayerEntry> stalking = new ArrayList<>();
            }

            public static final class AutoFish {
                public @Nullable Integer priority = null;
                public boolean enabled = false;
                public float yaw = 0.0f;
                public float pitch = 0.0f;
            }

            public static final class AntiAFK {
                public @Nullable Integer priority = null;
                public Actions actions = new Actions();
                public boolean enabled = true;

                public static final class Actions {
                    public boolean walk = true;
                    // we only need about 5-6 blocks in reality but adding a few extra here to be safe
                    // this isn't dependent on chunks loading but is more based on distance
                    public int walkDistance = 8;
                    // avoid going off ledges even when falls are non-fatal
                    public boolean safeWalk = true;
                    public long walkDelayTicks = 400;
                    public boolean swingHand = true;
                    public long swingDelayTicks = 3000;
                    public boolean rotate = true;
                    public long rotateDelayTicks = 300L;
                    public boolean jump = false;
                    public boolean jumpOnlyInWater = true;
                    public long jumpDelayTicks = 1L;
                    public boolean sneak = false;
                    public long sneakDelayTicks = 200L;
                }
            }

            public static final class Spook {
                public @Nullable Integer priority = null;
                public boolean enabled = false;
                public TargetingMode spookTargetingMode = TargetingMode.VISUAL_RANGE;

                public enum TargetingMode {
                    NEAREST,
                    VISUAL_RANGE
                }
            }

            public static final class ReplayMod {
                public boolean sendRecordingsToDiscord = false;
                public int maxRecordingTimeMins = 0;
                public AutoRecordMode autoRecordMode = AutoRecordMode.NONE;
                public int replayRecordingHealthThreshold = 5;
                public boolean fileIOUploadIfTooLarge = true;
                public boolean featureFlags = true;

                @Getter
                public enum AutoRecordMode {
                    NONE("off"),
                    PROXY_CONNECTED("proxyConnected"),
                    PLAYER_CONNECTED("playerConnected"),
                    HEALTH("health");
                    private final String name;

                    AutoRecordMode(String name) {
                        this.name = name;
                    }

                    public static String[] names() {
                        return Arrays.stream(AutoRecordMode.values()).map(AutoRecordMode::getName).toArray(String[]::new);
                    }
                }
            }

            public static final class Utility {
                public final Actions actions = new Actions();

                public static final class Actions {
                    public final AutoDisconnect autoDisconnect = new AutoDisconnect();
                    public final ActiveHours activeHours = new ActiveHours();
                }

                public static final class AutoDisconnect {
                    public boolean enabled = false;
                    public boolean healthDisconnect = true;
                    public boolean whilePlayerConnected = false;
                    public boolean autoClientDisconnect = false;
                    public int health = 5;
                    public boolean thunder = false;
                    public boolean cancelAutoReconnect = true;
                    // checks friends list, whitelist, and spectator whitelist
                    public boolean onUnknownPlayerInVisualRange = false;
                    public boolean mentionOnDisconnect = false;
                    public boolean onTotemPop = false;
                    public int minTotemsRemaining = 50;
                }

                public static final class ActiveHours {
                    public boolean enabled = false;
                    public boolean forceReconnect = false;
                    public boolean queueEtaCalc = true;
                    public boolean fullSessionUntilNextDisconnect = true;
                    public String timeZoneId = "Universal";
                    public final ArrayList<ActiveTime> activeTimes = new ArrayList<>();
                }
            }

            public static final class AutoReconnect {
                public boolean enabled = true;
                public int delaySeconds = 5;
                public int maxAttempts = 200;
            }

            public static final class AutoRespawn {
                public boolean enabled = true;
                public int delayMillis = 100;
            }

            public static final class Spammer {
                public boolean enabled = false;
                public boolean whilePlayerConnected = false;
                public boolean whisper = false;
                public long delayTicks = 200;
                public boolean randomOrder = false;
                public boolean appendRandom = false;
                public final ArrayList<String> messages = Lists.newArrayList(
                    "ZenithProxy on top!",
                    "I just skipped queue thanks to ZenithProxy!",
                    "Download ZenithProxy on GitHub today! It's free!"
                );
            }

            public static final class AutoReply {
                public boolean enabled = false;
                public int cooldownSeconds = 15;
                public String message = "I am currently AFK, check back later or message me on discord.";
            }

            public static final class CoordObfuscation {
                // all offsets in chunk coords
                public boolean enabled = false;
                public boolean validateSetup = true;
                public boolean exemptProxyAccount = false;
                public ObfuscationMode mode = ObfuscationMode.RANDOM_OFFSET;
                public boolean obfuscateBedrock = true;
                public boolean obfuscateChunkHeightmap = true;
                public boolean obfuscateChunkLighting = true;
                public boolean obfuscateBiomes = false;
                public String obfuscateBiomesKey = "plains";
                public int teleportOffsetRegenerateDistanceMin = 64; // minimum distance to regenerate coords at
                public int randomMinDistanceFromSelf = 100_000;
                public int randomMinDistanceFromSpawn = 100_000;
                public int randomMaxDistanceFromSpawn = 29_000_000;
                public int constantOffsetX = 0;
                public int constantOffsetZ = 0;
                public boolean constantOffsetNetherTranslate = true;
                public int constantOffsetMinSpawnDistance = 100000; // min distance to spawn the actual coords are before player is disconnected
                public int atLocationX = 0;
                public int atLocationZ = 0;
                public int delayPlayerLoginsAfterTpMs = 1000;
                public boolean disconnectWhileEyeOfEnderPresent = true;
                public boolean debugPacketLog = false;
                public boolean disconnectWhileNearOffsetBlocks = true;
                public enum ObfuscationMode {
                    RANDOM_OFFSET,
                    CONSTANT_OFFSET,
                    AT_LOCATION
                }
            }

            public static class ActionLimiter {
                public boolean enabled = false;
                // be careful with this, auto respawn will still respawn after they disconnect
                //  there is a position check at login so it should be ok, but the respawn will still go through
                public boolean allowRespawn = true;
                public boolean allowMovement = true;
                public int movementDistance = 1000; // distance from home coords
                public int movementHomeX = 0;
                public int movementHomeZ = 0;
                public int movementMinY = -64;
                public boolean allowEnderChest = true;
                public boolean allowBlockBreaking = true;
                // todo: dunno how to block this but still allow other interactions
//                public boolean allowBlockPlacing = true;
                public boolean allowInventory = true;
                public boolean allowUseItem = true;
                public boolean allowBookSigning = true;
                public boolean allowInteract = true;
                public boolean allowChat = true; // outbound chats
                public boolean allowServerCommands = true; // includes whispers
                public boolean exemptProxyAccount = false;
                public boolean itemsBlacklistEnabled = false;
                public final HashSet<String> itemsBlacklist = new HashSet<>();
            }
        }

        public static final class Server {
            public String address = "connect.2b2t.org";
            public int port = 25565;
        }

        public static final class ConnectionProxy {
            public boolean enabled = false;
            public ProxyInfo.Type type = ProxyInfo.Type.SOCKS5;
            public String host = "127.0.0.1";
            public int port = 7890;
            public String user = "";
            public String password = "";
        }
        public static final class AutoDrop {
            public @Nullable Integer priority = null;
            public boolean enabled = false;
            public Mode mode = Mode.WHITELIST;
            public enum Mode {
                ALL,
                BLACKLIST,
                WHITELIST
            }
            public ArrayList<String> items = new ArrayList<>();
            public int delayTicks = 10;
            public boolean dropStack = true;
            public boolean requiresRotation = false;
            public float yaw = 0.0f;
            public float pitch = 0.0f;
        }
    }

    public static final class Debug {
        public final PacketLog packetLog = new PacketLog();
        public final Server server = new Server();
        public boolean clearOldLogs = false;
        public boolean kickDisconnect = false;
        public boolean debugLogs = false;
        public boolean terminalDebugLogs = false;
        public boolean inventorySyncOnLogin = false;
        public boolean lockFile = true;
        public boolean passthroughResourcePacks = true;
        public boolean inputManagerDebugLogs = false;
        public boolean botPitchPrecisionClamping = true;
        public boolean botRotateBeforeInteract = true;
        public boolean inventoryRequestServerSyncOnAction = false;
        public boolean chainBreakSpeed2b2tFix = true;
        public boolean entityPushing = true;

        public static final class PacketLog {
            public boolean enabled = false;
            public boolean logLevelDebug = true;
            public PacketLogConfig clientPacketLog = new PacketLogConfig();
            public PacketLogConfig serverPacketLog = new PacketLogConfig();
            // todo: could be more flexible, but this can cover the most basic use cases
            public String packetFilter = "";

            public static final class PacketLogConfig {
                public boolean received = false;
                public boolean receivedBody = false;
                public boolean preSent = false;
                public boolean preSentBody = false;
                public boolean postSent = false;
                public boolean postSentBody = false;
            }
        }

        public static final class Server {
            public final Cache cache = new Cache();

            public static final class Cache {
                public boolean fullbrightChunkSkylight = true;
                public boolean fullbrightChunkBlocklight = false;
                // each map is 16kb, so 128 maps = ~2MB
                public int maxCachedMaps = 128;
            }
        }
    }

    public static final class Server {
        public final Bind bind = new Bind();
        public int compressionThreshold = 256;
        public int compressionLevel = -1;
        public boolean enabled = true;
        public final Extra extra = new Extra();
        public final Ping ping = new Ping();
        public final ServerViaVersion viaversion = new ServerViaVersion();
        public boolean verifyUsers = true;
        public boolean enforceMatchingConnectingAddress = false;
        public boolean acceptTransfers = true;
        public boolean onlyZenithTransfers = true;
        public String proxyIP = "localhost";
        public int queueStatusRefreshMinutes = 5; // how often to refresh queue lengths
        public boolean dynamicQueueEtaEquation = true;
        public boolean queueStatusRefreshWhileNotOn2b2t = true;
        public boolean healthCheck = true;
        public long playerListsRefreshIntervalMins = 1440L; // one day as default
        public final Spectator spectator = new Spectator();
        public final LoginRateLimiter loginRateLimiter = new LoginRateLimiter();
        public boolean connectionTestOnStart = true;
        public final PacketRateLimiter packetRateLimiter = new PacketRateLimiter();
        public boolean upnp = false;
        public boolean injectTablistFooter = true;
        public boolean welcomeMessages = true;
        public boolean updateServerIcon = true;
        public boolean preferLoginAsController = true;
        public final ChatSigning chatSigning = new ChatSigning();

        public static final class ChatSigning {
            public ChatSigningMode mode = ChatSigningMode.DISGUISED;

            public enum ChatSigningMode {
                PASSTHROUGH,
                DISGUISED,
                SYSTEM
            }
        }

        public static final class PacketRateLimiter {
            public boolean enabled = true;
            public double intervalSeconds = 7.0;
            public int maxPacketsPerInterval = 500;
            public boolean logRate = false;
        }

        public static final class LoginRateLimiter {
            public boolean enabled = true;
            public int rateLimitSeconds = 2;
        }

        public static final class Spectator {
            public boolean allowSpectator = true;
            public String spectatorEntity = "cat";
            public boolean spectatorPublicChatEnabled = true;
            public boolean fullCommandsEnabled = true;
            public boolean fullCommandsAcceptSlashCommands = true;
            public boolean fullCommandsRequireRegularWhitelist = true;
            public boolean playerCamOnJoin = false;
            public boolean whitelistEnabled = true;
            public ArrayList<PlayerEntry> whitelist = new ArrayList<>();
        }

        public static final class Bind {
            public String address = "0.0.0.0";
            public int port = 25565;
        }

        public static final class Extra {
            public final ServerTimeout timeout = new ServerTimeout();
            public final Whitelist whitelist = new Whitelist();
            public final ChatHistory chatHistory = new ChatHistory();
            public final ServerSwitcher serverSwitcher = new ServerSwitcher();

            public static class ServerSwitcher {
                public ArrayList<ServerSwitcherServer> servers = new ArrayList<>();
                public record ServerSwitcherServer(String name, String address, int port) { }
            }

            public static class ChatHistory {
                public boolean enable = false;
                public int seconds = 30;
                public int maxCount = 10;
                public boolean spectators = true;
            }

            public static final class Whitelist {
                public boolean enable = true;
                public final ArrayList<PlayerEntry> whitelist = new ArrayList<>();
                public String kickmsg = "no whitelist?";
                // Automatically adds the proxy client account to the whitelist if not present
                // does not remove any entries
                public boolean autoAddClient = true;
                // only checked when whitelist is disabled
                public final ArrayList<PlayerEntry> blacklist = new ArrayList<>();
            }

            public static final class ServerTimeout {
                public boolean enable = true;
                public int seconds = 30;
            }
        }

        public static final class Ping {
            public boolean enabled = true;
            public boolean onlinePlayers = false;
            public boolean onlinePlayerCount = true;
            public int maxPlayers = Integer.MAX_VALUE;
            public boolean lanBroadcast = true;
            public boolean responseCaching = true;
            // could probably be increased 2-3x without issue
            public int responseCacheSeconds = 10;
            public boolean logPings = true;
        }

        public static final class ServerViaVersion {
            public boolean enabled = true;
            public boolean autoRemoveFromPipeline = true;
        }

        public String getProxyAddress() {
            // if the proxy IP is not a DNS name and port is not present, append the port
            if (!this.proxyIP.contains(":")
                && (this.proxyIP.matches("[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+") || this.proxyIP.startsWith("localhost"))) // IP address
                return this.proxyIP + ":" + this.bind.port;
             else
                return this.proxyIP;
        }

        public String getProxyAddressForTransfer() {
            // get only the IP/address part. no port
            if (this.proxyIP.contains(":")) {
                return this.proxyIP.split(":")[0];
            } else {
                return this.proxyIP;
            }
        }

        public int getProxyPortForTransfer() {
            // get only the port part. no IP/address
            if (this.proxyIP.contains(":")) {
                return Integer.parseInt(this.proxyIP.split(":")[1]);
            } else {
                return this.bind.port;
            }
        }
    }

    public static class Plugins {
        public boolean enabled = true;
        public boolean blockCommandsUntilLoaded = false;
    }

    public static final class InteractiveTerminal {
        public boolean enable = true;
        public boolean logToDiscord = true;
        public boolean allowDumbTerminal = true;
        public boolean alwaysOnCompletions = true;
    }

    public static final class InGameCommands {
        public boolean enable = true;
        public boolean slashCommands = true;
        public boolean slashCommandsReplacesServerCommands = false;
        public boolean suggestions = true;
        public String prefix = "!";
        public boolean logToDiscord = true;
        public boolean allowWhitelistedToUseAccountOwnerCommands = false;
    }

    public static final class Discord {
        public boolean enable = false;
        public String token = "";
        public String channelId = "";
        public String accountOwnerRoleId = "";
        public String notificationMentionRoleId = "";
        public String prefix = ".";
        public boolean ignoreOtherBots = true;
        public boolean reportCoords = true;
        public boolean mentionRoleOnConnect = false;
        public boolean mentionRoleOnPlayerOnline = false;
        public boolean mentionRoleOnDisconnect = false;
        public boolean mentionRoleOnStartQueue = false;
        public boolean mentionRoleOnDeath = false;
        public boolean mentionRoleOnServerRestart = false;
        public boolean mentionRoleOnLoginFailed = false;
        public boolean clientConnectionMessages = true;
        public boolean mentionOnClientConnected = false;
        public boolean mcVersionMismatchWarning = true;
        public boolean mentionOnSpectatorConnected = false;
        public boolean mentionOnClientDisconnected = false;
        public boolean mentionOnNonWhitelistedClientConnected = false;
        public boolean mentionOnSpectatorDisconnected = false;
        public boolean mentionRoleOnPrioUpdate = true;
        public boolean mentionRoleOnDeviceCodeAuth = true;
        public boolean manageProfileImage = true;
        public boolean manageNickname = true;
        public boolean manageDescription = true;
        public boolean managePresence = true;
        public boolean showNonWhitelistLoginIP = true;
        public boolean isUpdating = false; // internal use for update command state persistence
        public final ChatRelay chatRelay = new ChatRelay();

        public static class ChatRelay {
            public boolean enable = false;
            public boolean ignoreQueue = true;
            public boolean mentionRoleOnWhisper = true;
            public boolean mentionRoleOnNameMention = true;
            public boolean mentionWhileConnected = false;
            public boolean connectionMessages = false;
            public boolean publicChats = true;
            public boolean whispers = true;
            public boolean serverMessages = true;
            public boolean deathMessages = true;
            public boolean sendMessages = true;
            public String channelId = "";
            public ArrayList<String> ignoreRegex = new ArrayList<>();
        }
    }

    public static final class Database {
        public boolean enabled = false;
        public String host = "";
        public int port = 5432;
        public String username = "";
        public String password = "";
        public boolean queueWaitEnabled = true;
        public boolean connectionsEnabled = true;
        public boolean chatsEnabled = true;
        public boolean deathsEnabled = true;
        public boolean unknownDeathDiscordMsg = true;
        public boolean queueLengthEnabled = true;
        public boolean restartsEnabled = true;
        public boolean playerCountEnabled = true;
        public boolean tablistEnabled = true;
        public boolean playtimeEnabled = true;
        public boolean timeEnabled = true;
        public final Lock lock = new Lock();

        public static final class Lock {
            // use "rediss://" for SSL connection
            public String redisAddress = "redis://localhost:7181";
            public String redisUsername = "";
            public String redisPassword = "";
        }
    }

    public static final class AutoUpdater {
        public int autoUpdateCheckIntervalSeconds = 300;
        // internal config, don't set this manually
        public boolean shouldReconnectAfterAutoUpdate = false;
    }
}
